security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
    role_hierarchy:
        ROLE_USER:
        ROLE_ADMIN: ROLE_USER #(access back-office)

    providers:
        in_memory:
            memory:
                users:
                    admin: { password: '$2y$13$eNLwMyIOR2bV2Ra5fCiaTOPM7GM1k.EJ4b/dqonRjAczxZTsTLeBK', roles: ['ROLE_ADMIN'] }
        app_user_provider:
            entity: { class: App\Entity\User, property: username }
        all:
            chain:
                providers: ['in_memory', 'app_user_provider']

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            guard:
                authenticator:
                - App\Security\LoginFormAuthenticator
            provider: all
            logout:
                path: logout
            switch_user: ~

    access_control:
    - { path: ^/admin14852, role: ROLE_ADMIN }